### ISSUE TITLE
Docker image doesn't build on develop

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#49]
Adding reactify to `package.json` solves the first issue:

```
+    "reactify": "^1.1.1",
```

But now there's this:

```
Step 15/22 : RUN (cd web && ../node_modules/.bin/browserify       --transform [ reactify --es6 --target es5 ]       --transfor
m brfs       --outfile bundle.js       js/entrypoint.js)
 ---> Running in 5a986b78daee
SyntaxError: Unexpected token (279:20) while parsing file: /home/app/code/web/js/users.jsx
    at Parser.pp$4.raise (/home/app/code/node_modules/acorn/dist/acorn.js:2610:13)
    at Parser.pp.unexpected (/home/app/code/node_modules/acorn/dist/acorn.js:637:8)
    at Parser.pp.expect (/home/app/code/node_modules/acorn/dist/acorn.js:631:26)
    at Parser.pp$2.parseBindingList (/home/app/code/node_modules/acorn/dist/acorn.js:1612:19)
    at Parser.pp$1.parseFunctionParams (/home/app/code/node_modules/acorn/dist/acorn.js:1189:22)
    at Parser.pp$1.parseFunction (/home/app/code/node_modules/acorn/dist/acorn.js:1176:8)
    at Parser.pp$3.parseExprAtom (/home/app/code/node_modules/acorn/dist/acorn.js:2082:17)
    at Parser.pp$3.parseExprSubscripts (/home/app/code/node_modules/acorn/dist/acorn.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/home/app/code/node_modules/acorn/dist/acorn.js:1932:17)
    at Parser.pp$3.parseExprOps (/home/app/code/node_modules/acorn/dist/acorn.js:1874:19)
```

@elmigranto Any idea why? Can you try `docker build -t ganomede/admin .` from the repo and fix this? Thanks!

**Comment by elmigranto** [comment]
This is old make command. Should be with babelify, see makefile in web folder. Reactify is not needed.

**Comment by elmigranto** [comment]
`make -C ./web build` should do it. Though docker-compose did that, sorry didn’t check.

**Comment by elmigranto** [comment]
Alright, should be buildable, I also reverted greenkeeper stuff, so build will also work.
